import sqlite3, json

conn = sqlite3.connect('data/cdrama.db')
cur = conn.cursor()

synopses = {
    "the-untamed": {
        "en": "Wei Wu Xian and Lan Wang Ji, two talented disciples of rival cultivation clans, uncover a dark secret buried for sixteen years. After Wei Wu Xian's tragic death, he is mysteriously resurrected and reunites with Lan Wang Ji to investigate a series of supernatural incidents plaguing the martial arts world. Together, they navigate political intrigue among the five great clans while unraveling the truth behind past betrayals and the rise of demonic cultivation.",
        "zh": "魏无羡与蓝忘机，两位来自不同修仙世家的杰出弟子，意外揭开了尘封十六年的黑暗秘密。魏无羡含冤而死后被神秘复活，与蓝忘机再度联手，调查修仙界接连发生的诡异事件。二人在五大世家的权力博弈中抽丝剥茧，逐步还原了当年的真相与魔道崛起的始末。",
        "vi": "Wei Wu Xian và Lan Wang Ji, hai đệ tử tài năng từ các tộc tu hành đối địch, tình cờ phát hiện bí mật đen tối đã bị chôn vùi suốt mười sáu năm. Sau cái chết bi thảm của Wei Wu Xian, anh được hồi sinh một cách bí ẩn và tái hợp với Lan Wang Ji để điều tra hàng loạt sự kiện siêu nhiên đang hoành hành trong giới võ lâm. Cùng nhau, họ vượt qua những âm mưu chính trị giữa năm đại tộc và lần ra sự thật đằng sau những phản bội trong quá khứ cùng sự trỗi dậy của ma đạo tu luyện.",
        "th": "Wei Wu Xian และ Lan Wang Ji ศิษย์ผู้มีความสามารถจากตระกูลบำเพ็ญพรตที่เป็นคู่แข่งกัน ค้นพบความลับมืดมนที่ถูกฝังมานานสิบหกปี หลังจาก Wei Wu Xian เสียชีวิตอย่างน่าเศร้า เขาได้รับการชุบชีวิตขึ้นมาอย่างลึกลับและได้กลับมาพบกับ Lan Wang Ji เพื่อสืบสวนเหตุการณ์เหนือธรรมชาติที่เกิดขึ้นในยุทธภพ ทั้งสองต้องเผชิญกับการเมืองอันซับซ้อนระหว่างห้าตระกูลใหญ่และคลี่คลายความจริงเบื้องหลังการทรยศในอดีตและการผงาดขึ้นของวิชามาร"
    },
    "word-of-honor": {
        "en": "Zhou Zi Shu, the former leader of a covert elite assassination unit serving the royal court, leaves his organization to live out his remaining days in freedom. On his journey, he encounters Wen Ke Xing, a mysterious and enigmatic figure from the dreaded Ghost Valley. The two form an unlikely alliance as they become entangled in a web of conspiracies surrounding legendary martial arts treasures and a decades-old vendetta, navigating the treacherous underworld of jianghu together.",
        "zh": "天窗组织首领周子舒为摆脱枷锁，以七年之寿换取自由之身，踏上漂泊江湖之路。途中他结识了来自鬼谷的神秘人物温客行，两人从互相试探到并肩同行，卷入了一场围绕武林至宝与陈年血仇的惊天阴谋。在波谲云诡的江湖中，他们携手揭开层层迷雾，也找到了彼此的救赎与归处。",
        "vi": "Chu Tử Thư, cựu thủ lĩnh của tổ chức ám sát tinh nhuệ phục vụ hoàng cung, rời bỏ tổ chức để sống những ngày tháng cuối đời trong tự do. Trên hành trình, hắn gặp Wen Ke Xing, một nhân vật bí ẩn và đầy bí ẩn từ Quỷ Cốc đáng sợ. Hai người hình thành một liên minh bất đắc dĩ khi bị cuốn vào mạng lưới âm mưu xoay quanh những báu vật võ công huyền thoại và mối thù truyền kiếp, cùng nhau dấn thân vào thế giới giang hồ đầy hiểm nguy.",
        "th": "Zhou Zi Shu อดีตผู้นำหน่วยลอบสังหารลับระดับสูงที่รับใช้ราชวงศ์ ลาออกจากองค์กรเพื่อใช้ชีวิตที่เหลืออย่างอิสระ ระหว่างทางเขาได้พบกับ Wen Ke Xing บุคคลลึกลับจากหุบเขาปีศาจ ทั้งสองสร้างพันธมิตรที่ไม่คาดคิดเมื่อ卷入เข้ากับเครือข่ายแผนสมคบคิดรอบสมบัติยุทธภพในตำนานและการแก้แค้นที่สั่งสมมานานหลายทศวรรษ ร่วมกันผจญภัยในยุทธภพอันเต็มไปด้วยอันตราย"
    },
    "nirvana-in-fire": {
        "en": "Twelve years after the unjust massacre of the elite Chi Yan Army, its sole survivor Lin Shu resurfaces in the capital under the alias Mei Chang Su, a frail but brilliant strategist. Determined to avenge seventy thousand innocent soldiers and restore his family's honor, he orchestrates an elaborate political chess game among the princes vying for the throne. With meticulous planning and unwavering resolve, Mei Chang Su manipulates factions, exposes conspiracies, and reshapes the destiny of the Southern Liang Dynasty.",
        "zh": "赤焰军七万将士蒙冤覆灭十二年后，幸存者林殊化名梅长苏重返帝都。他以病弱之躯化身天下谋士之首，暗中拨弄朝堂风云，为当年的沉冤昭雪。在诸皇子夺嫡的漩涡中，梅长苏以缜密的布局和坚定的信念，逐一揭开层层阴谋，为七万忠魂讨回公道，也改写了大梁王朝的命运。",
        "vi": "Mười hai năm sau cuộc thảm sát bất công của đội quân Xích Diễm tinh nhuệ, người sống sót duy nhất Lâm Thù xuất hiện trở lại tại kinh đô dưới bí danh Mai Trường Tô, một mưu sĩ ốm yếu nhưng thiên tài. Quyết tâm rửa hận cho bảy vạn binh sĩ vô tội và khôi phục danh dự gia tộc, anh dàn dựng một ván cờ chính trị phức tạp giữa các hoàng tử tranh giành ngai vàng. Với sự tính toán tỉ mỉ và ý chí kiên định, Mai Trường Tô điều khiển các phe phái, vạch trần âm mưu và thay đổi vận mệnh của triều đại Nam Lương.",
        "th": "สิบสองปีหลังจากการสังหารหมู่อย่างไม่เป็นธรรมของกองทัพChi Yan อัน精锐 ผู้รอดชีวิตเพียงคนเดียว Lin Shu กลับมาที่เมืองหลวงภายใต้ชื่อปลอม Mei Chang Su นักยุทธศาสตร์ผู้เฉลียวฉลาดแต่ร่างกายอ่อนแอ มุ่งมั่นที่จะล้างแค้นให้ทหารผู้บริสุทธิ์เจ็ดหมื่นนายและฟื้นฟูเกียรติยศของตระกูล เขาจัดฉากเกมการเมืองอันซับซ้อนระหว่างเจ้าชายที่แย่งชิงบัลลังก์ ด้วยแผนการอันรัดกุมและเจตจำนงอันแน่วแน่ Mei Chang Su ควบคุมฝ่ายต่างๆ เปิดโปงแผนสมคบคิด และเปลี่ยนชะตาของราชวงศ์ South Liang"
    },
    "love-between-fairy-and-devil": {
        "en": "A naive flower deity named Xiao Lan Hua accidentally revives Dong Fang Qing Cang, the feared Moon Supreme of the demonic realm, while trying to atone for her past life's sins. Bound by a fateful connection, the timid fairy and the once-all-powerful devil lord must rely on each other to survive the warring factions of the three realms. As their unlikely bond deepens, they discover that love may be the only force strong enough to heal ancient wounds and challenge the rigid laws of heaven and earth.",
        "zh": "天真善良的小兰花意外复活了被封印万年的月尊东方青苍，从此与这位令人闻风丧胆的魔族至尊结下了不解之缘。胆小怯懦的小仙子和曾经不可一世的魔尊不得不携手同行，在仙、月、人三界的纷争中求生。随着彼此的了解逐渐加深，他们发现爱才是弥合远古创伤、挑战天地法则的唯一力量。",
        "vi": "Một nữ thần hoa ngây thơ tên Tiểu Lan Hoa vô tình hồi sinh Đông Phương Thanh Thương, Nguyệt Chí Tôn đáng sợ của ma giới, khi cố chuộc tội cho kiếp trước. Bị ràng buộc bởi sợi dây duyên phận, nàng tiên nhút nhát và ma tôn từng quyền năng vô song phải dựa vào nhau để sinh tồn giữa các phe phái đang giao tranh trong tam giới. Khi mối liên kết bất ngờ của họ ngày càng sâu đậm, họ nhận ra rằng tình yêu có thể là sức mạnh duy nhất đủ lớn để hàn gắn những vết thương cổ xưa và thách thức luật lệ cứng nhắc của trời đất.",
        "th": "เทพธิดาดอกไม้นาม Xiao Lan Hua ทำใหั Dong Fang Qing Cang ผู้เป็นจันทราธิบดีผู้เกรงกลัวแห่งมาร界的ฟื้นคืนชีพโดยบังเอิญ ขณะพยายามชดใช้บาปในชาติก่อน ผูกพันด้วยโชคชะตา นางฟ้าขี้อายและจอมมารผู้เคยมีอำนาจล้นฟ้าต้องพึ่งพาซึ่งกันและกันเพื่อรอดชีวิตจากความขัดแย้งระหว่างสามภพ เมื่อสายสัมพันธ์ที่ไม่คาดคิดของพวกเขาลึกซึ้งขึ้น พวกเขาค้นพบว่าความรักอาจเป็นพลังเดียวที่แข็งแกร่งพอจะรักษาบาดแผลโบราณและท้าทายกฎแห่งสวรรค์และโลก"
    },
    "hidden-love": {
        "en": "Sang Zhi develops a secret crush on Duan Jia Xu, her older brother's charming college roommate, when she is just fourteen. Over the years, their paths cross and diverge as she grows from a shy schoolgirl into a confident young woman. When fate reunites them at university in his city, their everyday interactions slowly blossom from quiet admiration into genuine love, navigating the bittersweet challenges of an age gap and unspoken feelings.",
        "zh": "十四岁的桑稚对哥哥的大学室友段嘉许一见钟情，将这份暗恋深埋心底。此后数年，两人在成长中反复相遇又分离，她从怯生生的少女蜕变为独立的大学女生。当命运让他们在他所在的城市再度重逢，日常相处中的点点滴滴让这份沉默的倾慕悄然生根发芽，两人在年龄差距与未说出口的心意之间，慢慢走向彼此。",
        "vi": "Tang Zhi thầm yêu Duan Jia Xu, người bạn cùng phòng đại học điển trai của anh trai mình, khi cô mới mười bốn tuổi. Qua nhiều năm, con đường của họ giao nhau và rẽ ngang khi cô lớn lên từ một nữ sinh nhút nhát thành một phụ nữ trẻ tự tin. Khi số phận đưa họ tái hợp tại đại học ở thành phố của anh, những tương tác hằng ngày dần nở rộ từ ngưỡng mộ thầm lặng thành tình yêu đích thực, vượt qua những thử thách ngọt đắng của khoảng cách tuổi tác và những cảm xúc chưa từng nói ra.",
        "th": "Sang Zhi มีความรักลับๆ กับ Duan Jia Xu เพื่อนร่วมห้องมหาวิทยาลัยสุดหล่อของพี่ชายของเธอตั้งแต่เธออายุเพียงสิบสี่ปี ตลอดหลายปีที่ผ่านมาเส้นทางของพวกเขาพบกันและแยกจากกันในขณะที่เธอเติบโตจากเด็กนักเรียนขี้อายสู่สาวน้อยมั่นใจ เมื่อโชคชะตานำพวกเขากลับมาพบกันที่มหาวิทยาลัยในเมืองของเขา ปฏิสัมพันธ์ในชีวิตประจำวันค่อยๆ เบ่งบานจากความชื่นชมเงียบๆ สู่ความรักที่แท้จริง ท่ามกลางความท้าทายของช่องว่างอายุและความรู้สึกที่ยังไม่ได้พูด"
    },
    "story-of-minglan": {
        "en": "Set in the Northern Song Dynasty, this epic household saga follows Sheng Ming Lan, the unloved sixth daughter born to a concubine. After her mother's tragic death, Ming Lan is raised by her wise grandmother and learns to conceal her brilliance to survive a treacherous family full of scheming half-siblings and a neglectful father. Her quiet resilience catches the eye of Gu Ting Ye, the unconventional heir of a marquis household. Together, they navigate court politics, family intrigue, and a slow-burning romance that transforms both their lives.",
        "zh": "北宋年间，庶出六姑娘盛明兰自幼丧母，在祖母庇护下隐忍长大。面对嫡母刻薄、姐妹刁难和父亲漠视，她藏起聪慧锋芒，在深宅大院中小心求存。她的坚韧与智慧吸引了宁远侯府二公子顾廷烨的注意。两人在波诡云谲的朝堂与后宅中携手同行，从试探到交心，演绎了一段细水长流的爱情传奇。",
        "vi": "Lấy bối cảnh triều Bắc Tống, bộ sử thi gia tộc này kể về Thịnh Minh Lan, đứa con gái thứ sáu không được yêu thương sinh ra từ thiếp. Sau cái chết bi thảm của mẹ, Minh Lan được bà nội khôn ngoan nuôi dưỡng và học cách che giấu tài năng để sinh tồn trong một gia đình đầy rẫy những anh chị em mưu mô và người cha thờ ơ. Sự kiên cường lặng lẽ của nàng thu hút Cố Đình Diệp, người thừa kế khác thường của một phủ hầu tước. Cùng nhau, họ vượt qua chính trị triều đình, âm mưu gia tộc và một chuyện tình cháy chậm thay đổi cuộc đời cả hai.",
        "th": "ตั้งอยู่ในราชวงศ์เหนือซ่ง เรื่องราวมหากาพย์ตระกูลนี้ติดตาม Sheng Ming Lan ลูกสาวคนที่หกที่ไม่เป็นที่รักซึ่งเกิดจากนางสนม หลังจากการเสียชีวิตอันน่าเศร้าของแม่ Ming Lan ได้รับการเลี้ยงดูจากยายผู้เฉลียวฉลาดและเรียนรู้ที่จะซ่อนความอัจฉริยะเพื่อเอาชีวิตรอดในตระกูลที่เต็มไปด้วยพี่น้องต่างแม่ที่วางแผนและบิดาที่ละเลย ความยืดหยุ่นอย่างเงียบๆ ของเธอสะดุดตา Gu Ting Ye ทายาทที่ไม่ธรรมดาของตระกูลขุนนาง ทั้งสองนำทางผ่านการเมืองในราชสำนัก entangled ของครอบครัว และความรักที่ค่อยๆ ผลิดอกซึ่งเปลี่ยนแปลงชีวิตของพวกเขา"
    },
    "ashes-of-love": {
        "en": "Jin Mi, the daughter of the Flower Deity, has been raised on the Unproduced Pill that suppresses all emotions, leaving her unable to understand love. When she crosses paths with Xu Feng, the Crown Prince of the Bird Tribe who harbors a deep secret, and Run Yu, the composed Second Prince of Heaven, she becomes the unwitting center of a celestial love triangle. As forbidden feelings awaken within her, Jin Mi must navigate destiny, betrayal, and the devastating cost of love across the realms of heaven, earth, and the demon world.",
        "zh": "花神之女锦觅自幼被喂下陨丹，断情绝爱，不知情为何物。她先后邂逅了天界二殿下润玉和鸟族太子旭凤，却对两人的深情浑然不觉。当陨丹之效逐渐消退，压抑千年的情感汹涌而至，锦觅不得不在天界、花界与魔界的纠葛中做出抉择。一段跨越三界的旷世之恋，伴随着误解、牺牲与救赎，在爱恨交织中缓缓展开。",
        "vi": "Cẩm Mịch, con gái của Hoa Thần, được nuôi dưỡng bằng Bất Sinh Đansuppressing mọi cảm xúc, khiến nàng không thể hiểu được tình yêu. Khi nàng gặp Từ Phượng, Thái tử Điểu Tộc mang trong mình bí mật sâu kín, và Nhuận Ngọc, Nhị Điện Hạ điềm tĩnh của Thiên Giới, nàng vô tình trở thành trung tâm của một tam giác tình yêu thiên đình. Khi những cảm xúc cấm đoán bắt đầu thức tỉnh bên trong nàng, Cẩm Mịch phải đối mặt với số phận, sự phản bội và cái giá hủy diệt của tình yêu xuyên suốt các cõi trời, đất và thế giới yêu ma.",
        "th": "Jin Mi ธิดาแห่งเทพธิดาดอกไม้ ได้รับการเลี้ยงดูด้วยยาUnproduced Pill ที่กดอารมณ์ทั้งหมด ทำให้เธอไม่เข้าใจความรัก เมื่อเธอพบกับ Xu Feng มกุฎราชกุมารแห่งเผ่านกที่เก็บความลับลึกซึ้ง และ Run Yu องค์ชายที่สองผู้สุขุมแห่งสวรรค์ เธอกลายเป็นจุดศูนย์กลางของรักสามเส้าแห่งสวรรค์โดยไม่ตั้งใจ เมื่อความรู้สึกต้องห้ามเริ่มตื่นขึ้นภายในเธอ Jin Mi ต้องเผชิญกับโชคชะต การทรยศ และราคาอันร้ายแรงของความรักข้ามสามภพระหว่างสวรรค์ โลก และปีศาจ"
    },
    "the-longest-promise": {
        "en": "On the devastated Kong Sang Continent, a mortal named Tan Tai Jin is consumed by grief after the destruction of his kingdom and the death of his beloved. Desperate for revenge, he makes a devastating pact with a fallen god, trading away his emotions and his heart. Six centuries later, the heartless demon lord encounters Li Su Su, a compassionate mortal woman sent back in time to prevent his dark transformation. Their fates become intertwined as love, sacrifice, and destiny collide across two lifetimes.",
        "zh": "沧九旻本为景国质子澹台烬，历经屈辱与国破家亡之痛后坠入魔道，以无情之心称霸一方。六百年后，心怀慈悲的黎苏苏奉命穿越时空回到过去，试图阻止他走上毁灭之路。两人在宿命纠葛中相互救赎，却不得不面对仙魔对立的残酷现实。一段跨越轮回的虐恋，在爱与恨、牺牲与救赎之间徐徐展开。",
        "vi": "Trên Lục địa Khong Tang bị tàn phá, một người phàm tên Đàm Đài Tẫn bị giày vò bởi nỗi đau sau khi vương quốc bị phá hủy và người yêu qua đời. Tuyệt vọng trả thù, hắn lập một thỏa ước tàn khốc với một vị thần sa ngã, đánh đổi cảm xúc và trái tim mình. Sáu trăm năm sau, ma tôn vô tình gặp Lê Tô Tô, một phụ nữ phàm trần giàu lòng trắc ẩn được gửi ngược thời gian để ngăn chặn sự biến đổi đen tối của hắn. Số phận của họ đan xen khi tình yêu, sự hy sinh và định mệnh va chạm xuyên suốt hai kiếp.",
        "th": "บนทวีปKong Sang ที่ถูกทำลายล้าง ชายผู้名叫 Tan Tai Jin ถูกกลืนกินด้วยความโศกเศร้าหลังจากอาณาจักรถูกทำลายและคนรักเสียชีวิต สิ้นหวังที่จะแก้แค้น เขาทำข้อตกลงอันร้ายแรงกับเทพที่ล้มเหลว แลกเปลี่ยนอารมณ์และหัวใจของเขา หกศตวรรษต่อมา จอมมารไร้หัวใจได้พบกับ Li Su Su หญิง凡人ผู้เมตตาที่ถูกส่งย้อนเวลาเพื่อป้องกันความมืดของเขา โชคชะตาของพวกเขาพันกันเมื่อความรัก การเสียสละ และโชคชะตาชนกันในสองชาติภพ"
    },
    "reset": {
        "en": "College student Li Shi Qing and game designer Xiao He Yun find themselves trapped in a terrifying time loop after a catastrophic bus explosion. Each time they die, they wake up moments before the disaster, forced to relive the same horrifying cycle. As they struggle to break free, they uncover the hidden stories of the bus passengers and realize that preventing the explosion requires understanding every passenger's truth. Race against time unfolds as ordinary people are thrust into an extraordinary fight for survival and justice.",
        "zh": "大学生李诗情和游戏设计师肖鹤云在一辆公交车上遭遇了爆炸事故后，发现自己陷入了一个诡异的时间循环。每次死亡后都会回到爆炸前的同一刻，被迫反复经历这场噩梦。为了打破循环，他们必须查明爆炸的真相，揭开每一位乘客隐藏的故事与秘密。两个普通人在这段超现实的困境中，携手与命运抗争，追寻正义与生存的希望。",
        "vi": "Nữ sinh viên Lý Thi Tình và nhà thiết kế game Tiêu Hạc Vân thấy mình mắc kẹt trong một vòng lặp thời gian kinh hoàng sau một vụ nổ xe buýt thảm khốc. Mỗi lần họ chết, họ thức dậy ngay trước thảm họa, buộc phải sống lại cùng một chu kỳ đáng sợ. Khi cố gắng thoát ra, họ khám phá những câu chuyện ẩn giấu của các hành khách trên xe và nhận ra rằng ngăn chặn vụ nổ đòi hỏi phải hiểu sự thật của mỗi hành khách. Cuộc đua với thời gian diễn ra khi những người bình thường bị đẩy vào cuộc chiến phi thường vì sự sống còn và công lý.",
        "th": "นักศึกษามหาวิทยาลัย Li Shi Qing และนักออกแบบเกม Xiao He Yun发现自己ติดอยู่ในลูปเวลาที่น่ากลัวหลังจากระเบิดรถบัสอันหายนะ ทุกครั้งที่พวกเขาเสียชีวิต พวกเขาจะตื่นขึ้นก่อนหายนะเพียงไม่กี่อึดใจ ถูกบังคับให้ใช้ชีวิตในวงจรเดียวกันที่น่าสะพรึงกลัว ขณะที่พวกเขาพยายามหลุดพ้น พวกเขาเปิดเผยเรื่องราวที่ถูกซ่อนอยู่ของผู้โดยสารแต่ละคนและตระหนักว่าการป้องกันการระเบิดต้องเข้าใจความจริงของผู้โดยสารทุกคน การแข่งกับเวลาเริ่มขึ้นเมื่อคนธรรมดาถูกผลักเข้าสู่การต่อสู้ที่ไม่ธรรมดาเพื่อความอยู่รอดและความยุติธรรม"
    },
    "the-knockout": {
        "en": "Set across two timelines spanning twenty years, this gripping crime drama follows the parallel fates of An Xin, a principled police officer, and Gao Qi Qiang, a humble fish vendor who transforms into a ruthless crime boss. In 2000, their paths cross when An Xin shows kindness to the struggling Gao Qi Qiang. By 2021, Gao Qi Qiang has built a powerful criminal empire in Jinghai City, while An Xin, now gray-haired and battle-worn, still pursues justice. When a central inspection team arrives, the long-awaited reckoning finally begins.",
        "zh": "该剧横跨二十年时空，讲述了一正一邪两个男人命运的交织与对抗。2000年，热血刑警安欣偶遇被欺负的鱼贩高启强，出于善意施以援手。此后高启强一步步从受欺压的小商贩蜕变为只手遮天的黑恶势力头目。2021年，白发苍苍的安欣仍在坚守正义，中央督导组的到来为这场旷日持久的黑白较量画上了最终的句号。",
        "vi": "Bối cảnh trải dài hai dòng thời gian cách nhau hai mươi năm, bộ phim tội phạm hấp dẫn này theo dõi số mệnh song song của An Xin, một cảnh sát chính trực, và Gao Qi Qiang, một người bán cá khiêm tốn biến thành ông trùm tội phạm tàn bạo. Năm 2000, con đường họ giao nhau khi An Xin thể hiện lòng tốt với Gao Qi Qiang đang khó khăn. Đến năm 2021, Gao Qi Qiang đã xây dựng một đế chế tội phạm hùng mạnh tại thành phố Jinghai, trong khi An Xin, giờ đã bạc tóc và mòn mỏi, vẫn theo đuổi công lý. Khi một đoàn kiểm tra trung ương đến, cuộc quyết đấu được chờ đợi từ lâu cuối cùng cũng bắt đầu.",
        "th": "ดำเนินเรื่องข้ามสองเส้นเวลาที่ห่างกันยี่สิบปี อาชญากรรมระทึกนี้ติดตามชะตากรรมคู่ขนานของ An Xin เจ้าหน้าที่ตำรวจผู้ยึดมั่นในหลักการ และ Gao Qi Qiang พ่อค้าปลาต่ำต้อยที่เปลี่ยนเป็นเจ้าพ่ออาชญากรรมอันโหดร้าย ในปี 2000 เส้นทางของพวกเขาตัดกันเมื่อ An Xin แสดงความเมตตาต่อ Gao Qi Qiang ผู้กำลังลำบาก ภายในปี 2021 Gao Qi Qiang ได้สร้างอาณาจักรอาชญากรรมอันทรงพลังในเมือง Jinghai ขณะที่ An Xin ผมสีเทาและผ่านการต่อสู้นานมายังคงตามหาความยุติธรรม เมื่อทีมตรวจสอบกลางมาถึง การตัดสินที่รอคอยมานานก็เริ่มต้นขึ้น"
    },
    "meet-yourself": {
        "en": "After the sudden death of her best friend, hotel manager Xu Hong Dong's life falls into a deep slump. Seeking solace, she leaves the fast-paced city life behind and travels to Yun Miao Village near Dali in Yunnan Province. There she meets Xie Zhi Yao, a local who quit his well-paid corporate job to develop tourism in his hometown. Surrounded by the beauty of nature and a community of like-minded souls, Xu Hong Dong begins to heal, rediscover herself, and find unexpected love in this quiet, windswept place.",
        "zh": "闺蜜的突然离世让酒店经理许红豆的生活和工作陷入低谷。为了疗愈伤痛，她离开繁忙的都市，独自前往云南大理的云苗村。在那里，她遇到了辞去高薪工作回乡创业的本地青年谢之遥。在田园风光与淳朴乡情的滋养下，许红豆逐渐打开心结，重新审视人生方向，也在这片有风的地方收获了意外的爱情与前行的力量。",
        "vi": "Sau cái chết đột ngột của người bạn thân nhất, cuộc sống của quản lý khách sạn Từ Hồng Đậu rơi vào khủng hoảng sâu sắc. Tìm kiếm sự an ủi, cô rời bỏ cuộc sống thành phố nhộn nhịp và đến Làng Vân Miêu gần Đại Lý, tỉnh Vân Nam. Tại đó cô gặp Xie Zhi Yao, một người dân địa phương đã nghỉ việc văn phòng lương cao để phát triển du lịch quê hương. Được bao quanh bởi vẻ đẹp thiên nhiên và một cộng đồng những tâm hồn đồng điệu, Từ Hồng Đậu bắt đầu chữa lành, khám phá lại bản thân và tìm thấy tình yêu bất ngờ ở nơi yên tĩnh đầy gió này.",
        "th": "หลังจากการเสียชีวิตอย่างกะทันหันของเพื่อนสนิท ชีวิตของ Xu Hong Dong ผู้จัดการโรงแรมตกอยู่ในภาวะซึมเศร้าอย่างลึกซึ้ง เพื่อแสวงหาความสบายใจ เธอทิ้งชีวิตเมืองที่เร่งรีบและเดินทางไปยังหมู่บ้าน Yun Miao ใกล้ Dali ในมณฑลยูนนาน ที่นั่นเธอได้พบกับ Xie Zhi Yao ชาวท้องถิ่นที่ลาออกจากงานบริษัทเงินเดือนดีเพื่อพัฒนาการท่องเที่ยวในบ้านเกิด ล้อมรอบด้วยความงามของธรรมชาติและชุมชนแห่งวิญญาณที่คิดเหมือนกัน Xu Hong Dong เริ่มเยียวยา ค้นพบตัวเองอีกครั้ง และพบความรักที่ไม่คาดคิดในที่เงียบสงบและมีสายลมแห่งนี้"
    },
    "love-like-the-galaxy": {
        "en": "Left behind by her warrior parents since childhood, the sharp-tongued and fiercely independent Cheng Shao Shang learns to survive on her own in a household riddled with hostility. When the brilliant general Ling Buy Yi takes notice of her, their worlds collide in a tumultuous romance shaped by political upheaval and personal trauma. Set against the backdrop of a fledgling empire, the two must overcome family schemes, court conspiracies, and their own deep-seated wounds to build a love that rivals the brilliance of the stars.",
        "zh": "程少商自幼被父母遗弃在老家，在充满敌意的家族中学会了独立与隐忍。她聪慧倔强、口齿伶俐，却因出身低微处处受人轻视。骁勇善战的将军凌不疑对她一见倾心，两人在乱世纷争中相互扶持、彼此救赎。然而朝堂阴谋与家族恩怨接踵而至，两人必须在权力的漩涡与内心的伤痕之间找到相守的勇气，书写一段璀璨如星河的爱情传奇。",
        "vi": "Bị cha mẹ chiến binh bỏ lại từ nhỏ, Thừa Thiếu Thương sắc sảo và độc lập dữ dội phải học cách tự sinh tồn trong một gia đình đầy thù địch. Khi vị tướng tài ba Lăng Bất Nghi để mắt đến nàng, thế giới của họ va chạm trong một mối tình đầy sóng gió, được định hình bởi biến động chính trị và tổn thương cá nhân. Đặt trong bối cảnh một đế chế non trẻ, cả hai phải vượt qua âm mưu gia tộc, mưu kế triều đình và những vết thương sâu sắc của chính mình để xây dựng một tình yêu sánh ngang ánh sao rực rỡ.",
        "th": "ถูกทิ้งไว้โดยพ่อแม่ทหารตั้งแต่เด็ก Cheng Shao Shang ผู้ฉลาดและอิสระอย่างยิ่งต้องเรียนรู้ที่จะเอาชีวิตรอดด้วยตัวเองในตระกูลที่เต็มไปด้วยความเกลียดชัง เมื่อแม่ทัพผู้เฉลียวฉลาด Ling Buy Yi注意到เธอ โลกของพวกเขาชนกันในความรักที่ปั่นป่วนซึ่งถูกหล่อหลอมจากความปั่นป่วนทางการเมืองและบาดแผลส่วนตัว ท่ามกลางฉากหลังของอาณาจักรที่กำลังก่อตัว ทั้งสองต้องเอาชนะแผนการของตระกูล แผนการในราชสำนัก และบาดแผลลึกของตัวเอง เพื่อสร้างความรักที่รุ่งเรืองดุจดวงดาว"
    },
    "joy-of-life": {
        "en": "Fan Xian, a young man with mysterious origins and extraordinary abilities, grows up in a coastal city under the watchful eye of a powerful mentor. Upon reaching adulthood, he journeys to the capital to uncover the truth about his parentage and navigate the treacherous political landscape of the Qing Kingdom. Armed with sharp wit, formidable martial skills, and an enigmatic past, Fan Xian becomes entangled in a web of royal conspiracies, familial secrets, and life-or-death struggles that will determine the fate of an empire.",
        "zh": "范闲自小在海边长大，身世神秘却才华出众。在师父的悉心培养下，他文武双全，机智过人。成年后，范闲前往京都探寻身世之谜，却一头扎进了庆国波谲云诡的朝堂纷争之中。凭借过人的智慧和武功，以及深藏不露的过去，他在皇子争位、权臣角力的漩涡中游刃有余，一步步揭开层层谜团，在刀光剑影中书写属于自己的传奇。",
        "vi": "Phạm Nhàn, một chàng trai trẻ với nguồn gốc bí ẩn và khả năng phi thường, lớn lên tại một thành phố ven biển dưới sự giám sát của một người thầy quyền lực. Khi trưởng thành, anh đến kinh đô để tìm ra sự thật về thân thế và điều hướng bối cảnh chính trị đầy nguy hiểm của Vương quốc Khánh. Được trang bị trí tuệ sắc bén, kỹ năng võ thuật đáng gờm và quá khứ bí ẩn, Phạm Nhàn bị cuốn vào mạng lưới âm mưu hoàng gia, bí mật gia tộc và những cuộc đấu tranh sinh tử sẽ quyết định vận mệnh của cả đế chế.",
        "th": "Fan Xian ชายหนุ่มผู้มีต้นกำเนิดลึกลับและความสามารถพิเศษ เติบโตในเมืองชายฝั่งภายใต้การดูแลของพี่เลี้ยงผู้ทรงพลัง เมื่อเข้าสู่วัยผู้ใหญ่ เขาเดินทางไปยังเมืองหลวงเพื่อค้นหาความจริงเกี่ยวกับต้นกำเนิดของเขาและนำทางภูมิทัศน์การเมืองที่อันตรายของอาณาจักร Qing Armed ด้วยปัญญาอันเฉียบแหลม ทักษะศิลปะการต่อสู้ที่น่าเกรงขาม และอดีตที่ลึกลับ Fan Xian卷入เข้ากับเครือข่ายแผนสมคบคิดของราชวงศ์ ความลับของครอบครัว และการต่อสู้ระหว่างความเป็นและความตายที่จะกำหนดชะตากรรมของจักรวรรดิ"
    },
    "a-little-reunion": {
        "en": "This heartfelt drama centers on three families navigating the intense pressure of China's college entrance exam, the Gaokao. Follow three high school seniors and their parents as they face academic stress, family conflicts, and the emotional turbulence of adolescence. Each family grapples with unique challenges — from single parenting and blended families to the crushing weight of expectations — while discovering that love, understanding, and resilience can weather any storm on the road to adulthood.",
        "zh": "本剧聚焦中国高考这一人生重大节点，围绕三个面临不同困境的家庭展开。三位高三学生在学业压力、家庭矛盾和青春期的情感波动中挣扎前行，家长们也在焦虑与期望中寻找与孩子相处的方式。离异家庭、重组家庭、虎妈猫爸……每个家庭都有自己的难题与温情。在笑与泪交织的日子里，他们学会了理解、包容与共同成长。",
        "vi": "Bộ phim cảm động này xoay quanh ba gia đình vượt qua áp lực căng thẳng của kỳ thi tuyển sinh đại học Gaokao nổi tiếng của Trung Quốc. Theo chân ba học sinh cuối cấp trung học và cha mẹ họ khi đối mặt với áp lực học tập, xung đột gia đình và những biến động cảm xúc tuổi vị thành niên. Mỗi gia đình đối mặt với những thách thức riêng — từ nuôi con đơn thân, gia đình pha trộn đến sức nặng kỳ vọng — trong khi khám phá ra rằng tình yêu, sự thấu hiểu và kiên cường có thể vượt qua bất kỳ cơn bão nào trên đường trưởng thành.",
        "th": "ละครซึ้งกินใจนี้เน้นสามครอบครัวที่ต้องรับมือกับความกดดันจากการสอบเข้ามหาวิทยาลัยที่เข้มข้นของจีน ติดตามนักเรียนชั้นมัธยมปลายสามคนและผู้ปกครองขณะที่เผชิญกับความเครียดจากการเรียน ความขัดแย้งในครอบครัว และความปั่นป่วนทางอารมณ์ของวัยรุ่น แต่ละครอบครัวต้องรับมือกับความท้าทายที่ไม่ซ้ำกัน ตั้งแต่การเลี้ยงลูกคนเดียว ครอบครัวผสม ไปจนถึงน้ำหนักของความคาดหวัง ขณะที่ค้นพบว่าความรัก ความเข้าใจ และความยืดหยุ่นสามารถฝ่าพายุใดๆ บนเส้นทางสู่วัยผู้ใหญ่"
    },
    "story-of-kunning": {
        "en": "Jiang Xue Ning's obsession with power leads her to scheme her way onto the throne as empress, but her reign ends in tragedy when a rebellion destroys everything she holds dear. In her dying moments, she is granted a second chance and wakes up as her eighteen-year-old self, years before entering the palace. Determined to rewrite her fate, she tries to avoid the royal court entirely, only to be drawn back into its orbit as a princess's companion and a student of the brilliant but dangerous Imperial Tutor Xie Wei, the very man who orchestrated her downfall in a past life.",
        "zh": "姜雪宁前世为后位不择手段，最终在宫变中众叛亲离、含恨自尽。然而命运给了她重来的机会——她回到十八岁入宫之前，决心远离权力中心。然而阴差阳错，她再次被卷入宫廷漩涡：成为乐阳公主的伴读，又师从帝师谢危。这位前世一手将她推入深渊的冷面谋臣，如今正酝酿着一场更大的风暴。姜雪宁必须在改命与宿命之间找到出路，用爱与智慧化解前世种下的因果。",
        "vi": "Sự ám ảnh quyền lực của Khương Tuyết Ninh dẫn nàng đến mưu mô để lên ngôi hoàng hậu, nhưng triều đại của nàng kết thúc trong bi kịch khi một cuộc nổi dậy phá hủy mọi thứ nàng trân trọng. Trong những khoảnh khắc cuối đời, nàng được ban cơ hội thứ hai và thức dậy với thân phận mười tám tuổi, nhiều năm trước khi nhập cung. Quyết tâm viết lại số phận, nàng cố gắng tránh xa hoàng cung hoàn toàn, nhưng lại bị cuốn vào quỹ đạo của nó với tư cách bạn đồng hành của công chúa và học trò của Thái sư Tạ Nguy — chính người đã dàn dựng sự sụp đổ của nàng trong kiếp trước.",
        "th": "ความหลงใหลในอำนาจของ Jiang Xue Ning นำเธอไปสู่การวางแผนเพื่อขึ้นเป็นจักรพรรดินี แต่ยุคสมัยของเธอจบลงด้วยโศกนาฏกรรมเมื่อการก่อจลาจลทำลายทุกอย่างที่เธอรัก ในช่วงวาระสุดท้าย เธอได้รับโอกาสครั้งที่สองและตื่นขึ้นมาในฐานะตัวเธอเองในวัยสิบแปดปี หลายปีก่อนเข้าพระราชวัง มุ่งมั่นที่จะเขียนโชคชะตาใหม่ เธอพยายามหลีกเลี่ยงราชสำนักอย่างสิ้นเชิง แต่กลับถูกดึงเข้าสู่โคจรของมันในฐานะเพื่อนของเจ้าหญิงและศิษย์ของครูผู้สอนอันเฉียบแหลมแต่อันตราย Xie Wei ชายผู้จัดฉากความพินาศของเธอในชาติก่อน"
    }
}

for slug, syn in synopses.items():
    json_str = json.dumps(syn, ensure_ascii=False)
    cur.execute("UPDATE dramas SET synopses_json = ? WHERE slug = ?", (json_str, slug))
    print(f"Updated: {slug}")

conn.commit()
print(f"\nTotal rows affected: {cur.rowcount}")

# Verify
cur.execute("SELECT slug, length(synopses_json) FROM dramas WHERE slug IN ('the-untamed','word-of-honor','nirvana-in-fire','love-between-fairy-and-devil','hidden-love','story-of-minglan','ashes-of-love','the-longest-promise','reset','the-knockout','meet-yourself','love-like-the-galaxy','joy-of-life','a-little-reunion','story-of-kunning')")
for row in cur.fetchall():
    print(f"  {row[0]}: json_length={row[1]}")

conn.close()
